import os
import ast
import sys
from pathlib import Path
from typing import Set, List, Dict, Tuple


class PyInstallerHookGenerator:
    def __init__(self, project_root: Path):
        self.project_root = project_root
        self.hooks_dir = project_root / "hooks"
        self.hooks_dir.mkdir(exist_ok=True)
        self.local_modules = set()
        self.local_dirs = {project_root / "src", project_root / "lib", project_root / "ui"}

    def scan_plugin_directory(self, plugin_dir: Path) -> Dict[str, Tuple[str, Set[str]]]:
        """
        扫描插件目录，分析每个Python文件的依赖
        返回: {模块名: 依赖集合}
        """
        module_dependencies = {}

        for py_file in plugin_dir.rglob("*.py"):
            if py_file.name == "__init__.py":
                continue

            # 获取模块名（去掉.py后缀）
            module_name = py_file.stem
            if module_name:
                dependencies = self.analyze_file_dependencies(py_file)
                module_dependencies[module_name] = (py_file.parent.name, dependencies)

        return module_dependencies

    def analyze_file_dependencies(self, file_path: Path) -> Set[str]:
        """分析单个Python文件的依赖"""
        dependencies = set()

        # 获取项目根目录
        project_root = file_path.parent
        while project_root.name != Path.cwd().name:
            print(f"check local module at {project_root.as_posix()}")
            self._get_local_modules(project_root)
            project_root = project_root.parent

        try:
            with open(file_path, 'r', encoding='utf-8') as f:
                content = f.read()
                tree = ast.parse(content)
        except (SyntaxError, UnicodeDecodeError):
            return dependencies

        for node in ast.walk(tree):
            if isinstance(node, ast.Import):
                for alias in node.names:
                    if self._is_external_dependency(alias.name):
                        dep = alias.name.split('.')[0]
                        if self._is_external_dependency(dep):
                            dependencies.add(dep)
            elif isinstance(node, ast.ImportFrom) and node.module:
                if self._is_external_dependency(node.module):
                    dep = node.module.split('.')[0]
                    if self._is_external_dependency(dep):
                        dependencies.add(dep)

        return dependencies

    def _get_local_modules(self, project_root: Path):
        """获取项目中所有本地模块名"""
        self.local_modules.add(project_root.stem)
        # 遍历项目目录，收集所有Python模块名
        for py_file in project_root.rglob("*.py"):
            if py_file.stem != "__init__":
                self.local_modules.add(py_file.stem)
                # 获取相对路径作为模块名
                relative_path = py_file.relative_to(project_root)
                # 将路径转换为模块名（用点替换路径分隔符，去掉.py）
                module_name = str(relative_path).replace('/', '.').replace('\\', '.')
                self.local_modules.add(module_name.split('.')[0])  # 只取第一级

    def _is_external_dependency(self, dep: str) -> bool:
        """判断是否为外部依赖"""
        return (
                dep not in sys.builtin_module_names and
                dep not in self.local_modules and
                not dep.startswith('.')
        )  # 跳过相对导入

    def generate_hook_file(self, parent: str, module_name: str, dependencies: Set[str]):
        """为单个模块生成Hook文件"""
        hook_content = f'''# Hook file for {module_name}
# Automatically generated by PyInstallerHookGenerator

hiddenimports = {list(dependencies)}

# Additional data files if needed
# datas = [("path/to/data", "destination/path")]
'''

        hook_file = self.hooks_dir / f"hook-{parent}-{module_name}.py"
        with open(hook_file, 'w', encoding='utf-8') as f:
            f.write(hook_content)

        print(f"Generated hook file: {hook_file}")

    def generate_combined_hook(self, all_dependencies: Dict[str, Tuple[str, Set[str]]]):
        """生成一个包含所有依赖的合并Hook文件"""
        combined_deps = set()
        for deps in all_dependencies.values():
            combined_deps.update(deps[1])

        hook_content = f'''# Combined hook file for all dynamic modules
# Automatically generated by PyInstallerHookGenerator

hiddenimports = {list(combined_deps)}

# This hook covers all dependencies from dynamic modules
'''

        hook_file = self.hooks_dir / "hook-dynamic-modules.py"
        with open(hook_file, 'w', encoding='utf-8') as f:
            f.write(hook_content)

        print(f"Generated combined hook file: {hook_file}")

    def generate_spec_patch(self, all_dependencies: Dict[str, Tuple[str, Set[str]]]):
        """生成spec文件补丁内容"""
        combined_deps = set()
        for deps in all_dependencies.values():
            combined_deps.update(deps[1])

        spec_patch = f'''
# === 自动生成的spec文件补丁 ===
# 将以下内容添加到你的spec文件的Analysis部分：

hiddenimports = {list(combined_deps)}

# 或者在命令行中使用：
# arch -x86_64 .venv/bin/python -m PyInstaller your_script.py --hidden-import={" --hidden-import=".join(combined_deps)}
'''

        patch_file = self.project_root / "spec_patch.txt"
        with open(patch_file, 'w', encoding='utf-8') as f:
            f.write(spec_patch)

        print(f"Generated spec patch file: {patch_file}")

    def run(self, plugin_dir: Path, generate_individual_hooks=True, generate_combined=True):
        """主运行方法"""
        for local_dir in self.local_dirs:
            print(f"扫描插件目录: {local_dir}")
            if local_dir.exists():
                print(f"{local_dir} exists")
                self._get_local_modules(local_dir)
        print(f"扫描插件目录: {plugin_dir}")
        module_dependencies = self.scan_plugin_directory(plugin_dir)

        if not module_dependencies:
            print("未找到任何插件模块")
            return
        print(f"local module list: {self.local_modules}")
        print(f"找到 {len(module_dependencies)} 个模块")

        # 生成单独的Hook文件
        if generate_individual_hooks:
            for module_name, dependencies in module_dependencies.items():
                if dependencies:
                    self.generate_hook_file(dependencies[0], module_name, dependencies[1])
                    print(f"模块 '{module_name}' 的依赖: {dependencies}")

        # 生成合并的Hook文件
        if generate_combined:
            self.generate_combined_hook(module_dependencies)

        # 生成spec补丁
        self.generate_spec_patch(module_dependencies)

        print(f"\n打包时使用以下命令:")
        print(f"arch -x86_64 .venv/bin/python -m PyInstaller your_script.py --additional-hooks-dir={self.hooks_dir.relative_to(self.project_root)}")


# 使用示例
if __name__ == "__main__":
    # 配置参数
    PROJECT_ROOT = Path(__file__).parent  # 项目根目录
    PLUGIN_DIR = PROJECT_ROOT / "plugins"  # 动态模块所在目录

    # 创建生成器并运行
    generator = PyInstallerHookGenerator(PROJECT_ROOT)
    generator.run(PLUGIN_DIR)

a = "[1,2,3]"
b = a.split(".")
