# Hook file for setting
# Automatically generated by PyInstallerHookGenerator

hiddenimports = ['typing', 'dataclasses']

# Additional data files if needed
# datas = [("path/to/data", "destination/path")]
