# Hook file for worker_waveform
# Automatically generated by PyInstallerHookGenerator

hiddenimports = ['pathlib', 'typing', 'PySide6']

# Additional data files if needed
# datas = [("path/to/data", "destination/path")]
