# Hook file for main
# Automatically generated by PyInstallerHookGenerator

hiddenimports = ['os', 'datetime', 'threading', 'collections', 'typing', 'subprocess', 'shutil', 'pathlib', 'logging', 'traceback', 'PySide6']

# Additional data files if needed
# datas = [("path/to/data", "destination/path")]
