# Hook file for worker_analyzer
# Automatically generated by PyInstallerHookGenerator

hiddenimports = ['pathlib', 'PySide6', 'pandas', 'logging', 'importlib']

# Additional data files if needed
# datas = [("path/to/data", "destination/path")]
