# Hook file for keynote_manager
# Automatically generated by PyInstallerHookGenerator

hiddenimports = ['pathlib', 'keynote_parser', '__future__', 'typing', 'zipfile', 'PIL', 'io', 'os']

# Additional data files if needed
# datas = [("path/to/data", "destination/path")]
