# Hook file for excel
# Automatically generated by PyInstallerHookGenerator

hiddenimports = ['pathlib', 'typing', 'openpyxl', 'collections', 're']

# Additional data files if needed
# datas = [("path/to/data", "destination/path")]
