# Hook file for property
# Automatically generated by PyInstallerHookGenerator

hiddenimports = ['traceback', 'logging', 'typing', 'ast', 're']

# Additional data files if needed
# datas = [("path/to/data", "destination/path")]
