# Hook file for main
# Automatically generated by PyInstallerHookGenerator

hiddenimports = ['matplotlib', 'traceback', 'json', 'pathlib', 'logging', 'PySide6', 'datetime', 'typing', 'dataclasses', 'csv', 're', 'os']

# Additional data files if needed
# datas = [("path/to/data", "destination/path")]
