# Hook file for ppt_manager
# Automatically generated by PyInstallerHookGenerator

hiddenimports = ['pptx', '__future__', 'typing', 'PIL', 'io', 'os']

# Additional data files if needed
# datas = [("path/to/data", "destination/path")]
