# Hook file for Analyzer
# Automatically generated by PyInstallerHookGenerator

hiddenimports = ['numpy', 'matplotlib', 'pathlib', 'pandas', 'logging', 'abc', 'typing', 'openpyxl']

# Additional data files if needed
# datas = [("path/to/data", "destination/path")]
