# Hook file for gui
# Automatically generated by PyInstallerHookGenerator

hiddenimports = ['traceback', 'pathlib', 'logging', 'PySide6', 'importlib', 'datetime', 'typing', 'subprocess', 'os']

# Additional data files if needed
# datas = [("path/to/data", "destination/path")]
