# Hook file for setting
# Automatically generated by PyInstallerHookGenerator

hiddenimports = ['pathlib', 'typing', 'dataclasses']

# Additional data files if needed
# datas = [("path/to/data", "destination/path")]
