# Hook file for worker_summary
# Automatically generated by PyInstallerHookGenerator

hiddenimports = ['traceback', 'pathlib', 'pandas', 'logging', 'PySide6', 'openpyxl', 'collections']

# Additional data files if needed
# datas = [("path/to/data", "destination/path")]
