# Hook file for SPMI_Frame
# Automatically generated by PyInstallerHookGenerator

hiddenimports = ['PySide6', 'pathlib', 'logging']

# Additional data files if needed
# datas = [("path/to/data", "destination/path")]
