# Hook file for excel
# Automatically generated by PyInstallerHookGenerator

hiddenimports = ['collections', 'typing', 'openpyxl', 'pathlib', 're']

# Additional data files if needed
# datas = [("path/to/data", "destination/path")]
