# Hook file for main
# Automatically generated by PyInstallerHookGenerator

hiddenimports = ['logging', 'os', 'subprocess', 'typing', 'pathlib', 'shutil', 'threading', 'traceback', 'collections', 'datetime', 'PySide6']

# Additional data files if needed
# datas = [("path/to/data", "destination/path")]
