# Hook file for SWDAnalyzer
# Automatically generated by PyInstallerHookGenerator

hiddenimports = ['traceback', 'matplotlib', 'pathlib', 'pandas', 'logging', 'typing', 'collections']

# Additional data files if needed
# datas = [("path/to/data", "destination/path")]
