# Combined hook file for all dynamic modules
# Automatically generated by PyInstallerHookGenerator

hiddenimports = ['json', 'pathlib', 'logging', 'pandas', 'keynote_parser', 'importlib', 'typing', '__future__', 'dataclasses', 'ast', 'csv', 'subprocess', 'zipfile', 're', 'matplotlib', 'traceback', 'numpy', 'pptx', 'PySide6', 'datetime', 'abc', 'openpyxl', 'collections', 'PIL', 'io', 'os']

# This hook covers all dependencies from dynamic modules
