# Hook file for read_spec
# Automatically generated by PyInstallerHookGenerator

hiddenimports = ['pathlib', 'typing', 'pandas']

# Additional data files if needed
# datas = [("path/to/data", "destination/path")]
